# Welcome to Jekyll!
#
# Toto je soubor s hlavním nastavením. Na začátku je nastavení proměných, které
# je třeba přispůsobit si pro váš web. Později v anglicky popsané části jsou více
# technické nastavení
#

title: Piráti Železný Brod
email: zeleznybrod@pirati.cz 
description: >-
  Piráti - Železný Brod
# dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku
url: https://zeleznybrod.pirati.cz
keywords: piráti, železný brod, česká pirátská strana, svoboda, demokracie, jbc, jablonec, místní združení

administrator:
  email: marek.forster@pirati.cz # mail kam pujdou chybove vystupy

organization:
  name: Piráti Železný Brod
  shortName: Piráti Železný Brod
  contactUid: jan.tempel
  email: jan.tempel@pirati.cz
  phone: +420 777 123 456 789
  address: |
    Pixel - Pirátské centrum Jablonec n/N
    Generála Mrázka 413/4 
    468 01 Jablonec nad Nisou
  #residenceImg:
  mapLink: https://mapy.cz/zakladni?x=15.1709248&y=50.7244738&z=18&source=firm&id=12829995
  redmineLink: https://redmine.pirati.cz/projects

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Krajský kalendář
  id: vd0bm8kuaqdhmcjlnp6qj026fc@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=vd0bm8kuaqdhmcjlnp6qj026fc%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  #vyplně adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: https://www.facebook.com/PiratiZB/ 
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratiLiK

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/example.pirati.cz/
  branch: master

#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati

markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-environment-variables
  - jekyll-redirect-from  
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /komunalni-volby/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: 
        - foto
        - personContact
        - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: 
         - garant
         - program

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.4.0/gems/jekyll-theme-pirati-7.1.1/_sass 
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
